### ISSUE TITLE
Forget Password using Next-auth.js 

### ISSUE THREAD

**Issue by kkeval** [geovla93/merlyn-commerce#1]
Can you help me get done Password Recovery using Next auth, it seems you might have done it, it would be great if you share some thoughts on this.

**Comment by geovla93** [comment]
For password recovery you will need nodemailer. Basically. You need 2 endpoints. One for when the user requests a password reset ( /password-reset ). There you create a a unique token and store it in your database along with the userId and then you send an email to the user using nodemailer with a link containing his userId and token you created. That link must point to the other endpoint. There you check if userId and token match and if they do you change the password.. there are plenty of guides out there to help you further. This is not a next-auth thing.

**Comment by kkeval** [comment]
Hey can you provide me with a guide or thread to follow i've really stuck here, some help would be great
